# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_consagracao', models.DateField(blank=True, null=True, verbose_name='data de consagração')),
                ('data_apresentacao', models.DateField(blank=True, null=True, verbose_name='data de apresentação')),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('cartao', models.BooleanField(verbose_name='cartão')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='função')),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome do pai')),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome da mãe')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_nascimento', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='estado')),
                ('pais_nascimento', models.CharField(default='Brasil', max_length=50, verbose_name='país de nascimento')),
                ('estado_civil', models.CharField(blank=True, choices=[('so', 'solteiro'), ('ca', 'casado'), ('di', 'divorciado'), ('ou', 'outros')], default='ou', max_length=2, null=True, verbose_name='estado civil')),
                ('rg', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('efi', 'ensino fundamental incompleto'), ('efc', 'ensino fundamental completo'), ('emi', 'ensino médio incompleto'), ('emc', 'ensino médio completo'), ('esi', 'ensino superior incompleto'), ('esc', 'ensino superior completo'), ('ou', 'outros'), ('ind', 'indefinido')], default='ind', max_length=3, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='profissão')),
                ('data_batismo', models.DateField(blank=True, null=True, verbose_name='data de batismo')),
                ('igreja_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='igreja cidade')),
                ('admitido', models.CharField(blank=True, choices=[('bat', 'batismo'), ('ca', 'carta'), ('acl', 'aclamação'), ('ind', 'indefinido')], default='ind', max_length=3, null=True, verbose_name='admitido por')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('endereco', models.CharField(blank=True, max_length=150, null=True, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('fone', models.CharField(blank=True, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
    ]
